# Generated by Django 4.1.1 on 2022-09-26 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_comments_alter_comment_creator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_id',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
